version: '3'
services:
  mongo:
    image: 'mongo:4.0.4'
    volumes:
    - mongodb:/data/db
    - mongodb_config:/data.configdb
    ports:
      - '27017:27017'

volumes:
  mongodb:
  mongodb_config: